# Generated by Django 4.2.28 on 2026-05-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название компании')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название датасета')),
                ('file', models.FileField(upload_to='datasets/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('status', models.CharField(choices=[('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('ready', 'Готов'), ('error', 'Ошибка')], default='uploading', max_length=20, verbose_name='Статус обработки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_count', models.IntegerField(default=0, verbose_name='Количество строк')),
                ('columns_count', models.IntegerField(default=0, verbose_name='Количество колонок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Датасет',
                'verbose_name_plural': 'Датасеты',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_column_name', models.CharField(max_length=255, verbose_name='Название колонки у пользователя')),
                ('standard_name', models.CharField(choices=[('goods_name', 'Название товара'), ('goods_category', 'Категория товара'), ('quantity', 'Количество'), ('price', 'Цена'), ('total', 'Сумма'), ('date', 'Дата'), ('supplier', 'Поставщик'), ('customer', 'Клиент/Покупатель'), ('order_id', 'Номер заказа'), ('status', 'Статус'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Стандартное название в системе')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='main.dataset')),
            ],
            options={
                'verbose_name': 'Маппинг колонки',
                'verbose_name_plural': 'Маппинги колонок',
                'unique_together': {('dataset', 'user_column_name')},
            },
        ),
    ]
