# Generated by Django 4.2.28 on 2026-05-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_dashboardwidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='standard_name',
            field=models.CharField(choices=[('goods_name', 'Название товара'), ('goods_category', 'Категория товара'), ('quantity', 'Количество'), ('price', 'Цена'), ('total', 'Сумма / Выручка'), ('cost', 'Себестоимость'), ('date', 'Дата'), ('time', 'Время'), ('datetime', 'Дата и Время'), ('supplier', 'Поставщик'), ('customer', 'Клиент / Покупатель'), ('customer_group', 'Группа клиентов'), ('order_id', 'Номер заказа'), ('status', 'Статус'), ('payment_method', 'Способ оплаты'), ('store', 'Магазин / Точка'), ('city', 'Город / Регион'), ('manager', 'Менеджер / Сотрудник'), ('discount', 'Скидка'), ('promo', 'Промокод / Акция'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Стандартное название в системе'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя сотрудника')),
                ('generated_password', models.CharField(max_length=50, verbose_name='Сгенерированный пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='main.dataset', verbose_name='Привязанный датасет')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
    ]
